graph TD
A(Augmentation de la population de lièvres) -- Les lynx ont assez à manger et se reproduisent --> B(Augmentation de la population de lynx)
B -- Les lynx mangent de plus en plus de lièvres --> C(Diminution de la population de lièvres)
C-- Les lynx n'ont plus assez à manger et ne se reproduisent plus --> D(Diminutuon de la population de lynx)
D -- Les lynx mangent moins de lièvres --> E(Reproduction des lièvres)
E --> A 