graph LR

    subgraph Expiration 

   AF((Alvéoles Pulmonaires))--> AE(Bronchioles)--> AD(Bronches) --> AC(Trachée) --> AB(Nez / Bouche) -->  AA{Extérieur} 

    end

    subgraph Inspiration

    A{Extérieur}--> B(Nez / Bouche) --> C(Trachée) --> D(Bronches) --> E(Bronchioles) --> F((Alvéoles Pulmonaires))

    end


    

   


