graph LR
A{Extérieur}--Inspiration-->B(Nez / Bouche) --Inspiration--> C(Trachée) --Inspiration--> D(Bronches) --Inspiration--> E(Bronchioles) --Inspiration--> F((Alvéoles Pulmonaires))
F --Expiration--> E --Expiration--> D --Expiration--> C--Expiration--> B --Expiration-->A

