enabled: true
dropdown:
  enabled: true
production-mode: true
menu_langswitcher: false
menu_search: true
menu_login: false
themeSlogan: null
custom_logo_enabled: false
custom_logo_width: 100
blog-page: /blog
featured: false
featured_tag: featured
featured_number: 3
copyright:
  text: '(c) www.profcollet.fr - Tous droits réservés'
contact:
  text: null
  email: contact@profcollet.fr
  phone: '(555) 555-5555'
  street: '123 Any Street'
  city: AnyTown
  state: CA
  zip: '12345'
social_enabled: false
custommenu_enabled: false
custom_logo: {  }
custom_logo_mobile: {  }
custommenu:
  -
    text: null
    icon: null
    url: null
    target: _self
