enabled: true
dropdown:
  enabled: true
production-mode: true
menu_langswitcher: true
menu_search: true
menu_login: true
themeSlogan: null
custom_logo_enabled: false
custom_logo_width: 100
blog-page: /blog
featured: true
featured_tag: featured
featured_number: 3
copyright:
  text: '(c) www.profcollet.fr - Tous droits réservés'
contact:
  text: null
  email: contact@profcollet.fr
  phone: null
  street: null
  city: null
  state: null
  zip: null
social_enabled: true
custommenu_enabled: false
custom_logo: {  }
custom_logo_mobile: {  }
