graph
subgraph Acivité 2

subgraph Etape 1

    A[Début] --> B((1))
    A --> C((2))
    A --> D((3))
    A --> E((4))
    A --> F((5))
    A --> G((6))
    A --> H((7))
    A --> I((8))
    A --> J((9))
    A --> K((10))
    B --> AA{Jupiter}
    C --> AA  
    D --> AA  
    E --> AA 
    F --> AA
    G --> AA 
    H --> AB{Saturne}
    I --> AB 
    J --> AB

end 

subgraph Etape 2

    K --> K1((1)) 
    K --> K2((2)) 
    K --> K3((3)) 
    K --> K4((4)) 
    K --> K5((5)) 
    K --> K6((6)) 
    K --> K7((7)) 
    K --> K8((8))
    K5 --> AC{Neptune}
    K1--> AB
    K2--> AB
    K3--> AB
    K7 --> AD{Uranus}
    K4 --> AC
    K6 --> AD
    

end

subgraph Etape 3

K8-->KK1((1))
K8-->KK2((2))
K8-->KK3((3))
K8-->KK4((4))
K8-->KK5((5))
K8-->KK6((6))
K8-->KK7((7))
K8-->KK8((8))

KK1--> AB
KK2--> AB
KK3--> AB
KK4 --> AB

KK5 --> AD
KK6 --> AD

KK7 --> AA

end
   
subgraph Etape 4

KK8 --> J1((1))
KK8 --> J2((2))
KK8 --> J3((3))
KK8 --> J4((4))
KK8 --> J5((5))
KK8 --> J6((6))
KK8 --> J7((7))
KK8 --> J8((8))
KK8 --> J9((9))
KK8 --> J10((10))

J1 --> AE{Terre}
J2 --> AE
J3 --> AE

J4--> AF{Vénus}
J5--> AF

J6 --> AC
J7--> AC
J8--> AC
J9--> AC


end

subgraph Etape 5
J10-->JJ1((1))
J10-->JJ2((2))
J10-->JJ3((3))
J10-->JJ4((4))
J10-->JJ5((5))

JJ1--> AF
JJ2 --> AF

JJ3 --> AG{Mars}
JJ4 --> AG

JJ5 --> AH{Mercure}

end
  end
  