title: www.profcollet.fr
default_lang: fr
author:
  name: 'COLLET David'
  email: contact@profcollet.fr
taxonomies:
  - category
  - tag
metadata: null
summary:
  enabled: false
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
