graph LR


A(... vivant);
AA(Respire);
AB(Grandit);
AC(Se nourrit);
AD(Se reproduit);
AE(Ne se déplace pas obligatoirement);


B(...technique);
BA(frabriqué par l'Homme);
BB(répond à un besoin);

C(...physique);
CA(naturel);
CB(n'est pas vivant, et n'est pas frabriqué par l'Homme);

A==>AA & AB & AC & AD & AE
B==>BA & BB
C==> CA & CB

D(Un obejt peut être ...)

D==>A & B & C
