graph LR
A[Culture de la pomme de terre sur Mars]
B[Avantages]
C[Diversification de l'alimentation]
D[Rapidité de la reproduction par bouturage]
E[Richesse en amidon]
F[Défis]
G[Absence de matière organique dans le sol]
H[Atmosphère martienne non propice à la vie végétale ou animale]
I[Création d'un sol riche en matière organique]
J[Mise en place d'un éclairage artificiel]
K[Gestion des déchets organiques]
L[Alternatives]
M[Cultures alternatives : blé, maïs, riz]
N[Alternatives à la culture de plantes : champignons, insectes comestibles]

A-->B
B-->C
B-->D
B-->E
A-->F
F-->G
F-->H
F-->I
F-->J
F-->K
A-->L
L-->M
L-->N
